# Generated by Django 2.1.3 on 2018-12-28 13:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndmu', '0005_auto_20181228_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
